### ISSUE TITLE
Help, I can't npm start the project successfully in mac osx 10.12.1, thanks

### ISSUE THREAD

**Issue by chimmyhuang** [lobinroromens/antd-dva-admin-starter#1]
Hi lobinroromens, 

     The steps :

     1. git clone https://github.com/lobinroromens/antd-dva-admin-starter.git
     
     2. npm install

     3. npm start

      The output 

> @ start /Volumes/DATA/sf/antd/antd-dva-admin-starter
> dora --plugins "proxy,webpack,webpack-hmr"

          proxy: load rule from proxy.config.js
(node:40724) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
📦  4/8 build modulesYou are using prebuilt antd,
please use https://www.npmjs.com/package/babel-plugin-antd to reduce app bundle size.
📦  15/16 build modules
webpack: bundle build is now finished.
Hash: d70f8ff0b57176c524a5
Version: webpack 1.12.15
Time: 1870ms
        Asset     Size  Chunks             Chunk Names
    common.js  24.3 kB       0  [emitted]  common
     index.js  80.8 kB    1, 0  [emitted]  index
common.js.map  25.7 kB       0  [emitted]  common
 index.js.map  88.6 kB    1, 0  [emitted]  index
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]
chunk    {1} index.js, index.js.map (index) 78.4 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] ./~/html-entities/lib/html5-entities.js 49 kB {1} [built]
    [2] ./~/ansi-html/index.js 4.26 kB {1} [built]
    [3] ./~/ansi-regex/index.js 135 bytes {1} [built]
    [4] ./~/html-entities/index.js 231 bytes {1} [built]
    [5] ./~/html-entities/lib/html4-entities.js 6.57 kB {1} [built]
    [6] ./~/html-entities/lib/xml-entities.js 2.98 kB {1} [built]
    [7] ./~/querystring/decode.js 2.4 kB {1} [built]
    [8] ./~/querystring/encode.js 2.09 kB {1} [built]
    [9] ./~/querystring/index.js 127 bytes {1} [built]
   [10] ./~/strip-ansi/index.js 161 bytes {1} [built]
   [11] (webpack)-hot-middleware/client-overlay.js 1.74 kB {1} [built]
   [12] (webpack)-hot-middleware/client.js?path=http%3A%2F%2F127.0.0.1%3A8000%2F__webpack_hmr&reload=true 4.6 kB {1} [built]
   [13] (webpack)-hot-middleware/process-update.js 3.88 kB {1} [built]
   [14] (webpack)/buildin/module.js 251 bytes {1} [built]

ERROR in ./src/index.js
Module build failed: Error: Plugin 3 specified in "base" provided an invalid property of "Affix"
    at Plugin.init (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:148:12)
    at /Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Volumes/DATA/sf/antd/antd-dva-admin-starter/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
 @ multi index

   How to fixed? 

    Thanks.

**Comment by luofei2011** [comment]
@chimmyhuang 

1. Edit `webpack.config.js`, change the `antd` babel config to:

```javascript
webpackConfig.babel.plugins.push(['import', {
  libraryName: 'antd',
  style: 'css',  // if true, use less
}]);
```

2. Install import plugin for babel

```bash
npm install babel-plugin-import --save-dev
```

**Comment by Tim1023** [comment]
@luofei2011 还是不行
